source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KeepBackgroundCell_Example', :exclusive => true do
  pod "KeepBackgroundCell", :path => "../"
end

target 'KeepBackgroundCell_Tests', :exclusive => true do
  pod "KeepBackgroundCell", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
